FROM node:22-alpine
WORKDIR /app

COPY package.json package-lock.json ./
COPY tsconfig.base.json ./
COPY packages ./packages/
COPY apps/portal ./apps/portal/

RUN npm install --workspace=apps/portal --include-workspace-root

WORKDIR /app/apps/portal
RUN npm run build

WORKDIR /app
EXPOSE 3000
CMD ["npm", "run", "start", "--workspace=apps/portal"]
