[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[start]
cmd = "npx prisma migrate deploy --schema=../../prisma/schema.prisma && node dist/apps/api/src/index.js"
